import type { SiparisTakipApiYaniti, SiparisTakipFiltreleri } from "@/lib/eclub/hediyeTakip/siparisTakip";
export const BOS_SIPARIS_TAKIP_FILTRELERI: SiparisTakipFiltreleri = { eczane_id: null, urun_id: null, durum: null, baslangic: null, bitis: null, offset: 0, limit: 30 };
export default function SiparisTakipFiltreleri({ deger, secenekler, onDegistir }: { deger: SiparisTakipFiltreleri; secenekler: SiparisTakipApiYaniti["filtre_secenekleri"]; onDegistir: (deger: SiparisTakipFiltreleri) => void }) {
  const alan = (key: keyof SiparisTakipFiltreleri, value: string) => onDegistir({ ...deger, [key]: value || null, offset: 0 });
  return <section aria-label="Sipariş takip filtreleri" className="rounded-2xl border border-[#dfe7f1] bg-white p-3 shadow-sm md:p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5">
    <label htmlFor="siparis-takip-eczane" className="text-[10px] font-extrabold uppercase tracking-wide text-[#7d8fa5]">Eczane<select id="siparis-takip-eczane" className="mt-1 w-full rounded-xl border p-2 text-xs" value={deger.eczane_id ?? ""} onChange={(event) => alan("eczane_id", event.target.value)}><option value="">Tüm eczaneler</option>{secenekler.eczaneler.map((item) => <option key={item.id} value={item.id}>{item.etiket}</option>)}</select></label>
    <label htmlFor="siparis-takip-urun" className="text-[10px] font-extrabold uppercase tracking-wide text-[#7d8fa5]">Ürün<select id="siparis-takip-urun" className="mt-1 w-full rounded-xl border p-2 text-xs" value={deger.urun_id ?? ""} onChange={(event) => alan("urun_id", event.target.value)}><option value="">Tüm ürünler</option>{secenekler.urunler.map((item) => <option key={item.id} value={item.id}>{item.etiket}</option>)}</select></label>
    <label htmlFor="siparis-takip-durum" className="text-[10px] font-extrabold uppercase tracking-wide text-[#7d8fa5]">Durum<select id="siparis-takip-durum" className="mt-1 w-full rounded-xl border p-2 text-xs" value={deger.durum ?? ""} onChange={(event) => alan("durum", event.target.value)}><option value="">Tüm durumlar</option><option value="onay_bekliyor">Onay bekliyor</option><option value="depo_surecinde">Depo sürecinde</option><option value="teslimat_bekliyor">Teslimat bekliyor</option><option value="tamamlandi">Tamamlandı</option><option value="iptal">İptal</option></select></label>
    <label htmlFor="siparis-takip-baslangic" className="text-[10px] font-extrabold uppercase tracking-wide text-[#7d8fa5]">Başlangıç<input id="siparis-takip-baslangic" type="date" className="mt-1 w-full rounded-xl border p-2 text-xs" value={deger.baslangic ?? ""} onChange={(event) => alan("baslangic", event.target.value)} /></label>
    <label htmlFor="siparis-takip-bitis" className="text-[10px] font-extrabold uppercase tracking-wide text-[#7d8fa5]">Bitiş<input id="siparis-takip-bitis" type="date" className="mt-1 w-full rounded-xl border p-2 text-xs" value={deger.bitis ?? ""} onChange={(event) => alan("bitis", event.target.value)} /></label>
  </div><button type="button" className="mt-3 text-xs font-extrabold text-[#237ac8]" onClick={() => onDegistir({ ...BOS_SIPARIS_TAKIP_FILTRELERI })}>Filtreleri temizle</button></section>;
}
