-- UTT izleme oturum modeli — SALT OKUMA ön kontrol rehberi.
-- Supabase SQL Editor her çalıştırmada tek sonuç kümesi gösterebildiği için
-- kontroller aşağıdaki bağımsız dosyalara ayrılmıştır.
--
-- Canlı DB'de yalnız İskender tarafından, uygulama SQL'inden ÖNCE ve sırayla:
-- 1. utt_izleme_on_kontrol/01_gecis_kapsami.sql
-- 2. utt_izleme_on_kontrol/02_kazanim_mukerrerleri.sql
-- 3. utt_izleme_on_kontrol/03_cevap_mukerrerleri.sql
-- 4. utt_izleme_on_kontrol/04_kayip_mukerrerleri.sql
-- 5. utt_izleme_on_kontrol/05_cevaplanmis_tamamlanmis.sql
--
-- Dosyaların tamamı salt okumadır; hiçbir satır veya şema değiştirmez.
-- 02, 03 ve 04 numaralı sorgular boş dönmeden geçiş SQL'i çalıştırılmaz.
