require("dotenv").config({ path: ".env.local", quiet: true });
const assert=require("node:assert/strict"); const {randomUUID}=require("node:crypto"); const {Client}=require("pg");
const sorular=Array.from({length:10},(_,i)=>({soru_metni:`Hazır araç sorusu ${i+1}`,secenekler:["A","B","C","D"].map((harf,j)=>({harf,metin:`Seçenek ${harf}`,dogru:j===0}))}));
async function main(){const c=new Client({connectionString:process.env.DATABASE_URL});await c.connect();try{await c.query("BEGIN");
 const t=(await c.query(`SELECT t.* FROM public.talepler t JOIN public.kullanicilar k ON k.kullanici_id=t.uretici_id AND k.aktif_mi=true WHERE t.ogrenme_araci_turu='gorsel' ORDER BY t.created_at DESC LIMIT 1`)).rows[0];assert.ok(t);
 const sonuc=[]; for(const tur of ["podcast","gorsel","flip_pdf"])for(const hazirSoru of [false,true]){await c.query("SAVEPOINT v");const varyant=hazirSoru?"V4":"V2";
  const veri={firma_id:t.firma_id,takim_id:t.takim_id,egitim_turu:t.egitim_turu,hedef_roller:t.hedef_roller,icerik_turu:t.icerik_turu,ogrenme_araci_turu:tur,ogrenme_araci_tercihleri:tur==="podcast"?{transkript_istendi:false}:{},urun_id:t.urun_id,teknik_id:t.teknik_id,urun_adi:t.urun_adi,aciklama:`${tur} ${varyant} rollback`,hazir_video:true,hazir_soru_seti:hazirSoru,hazir_soru_seti_verisi:hazirSoru?sorular:null,soru_seti_buyuklugu:10,secenek_sayisi:4,video_basi_soru_sayisi:2};
  const talep=(await c.query("SELECT public.talep_atomik_olustur($1,$2,$3::jsonb) sonuc",[t.uretici_id,randomUUID(),JSON.stringify(veri)])).rows[0].sonuc;
  const mime=tur==="gorsel"?"image/png":tur==="flip_pdf"?"application/pdf":"audio/mpeg";const meta={depolama_dogrulamasi:{dosya_imzasi:{dogrulandi:true},dosya_boyutu:{dogrulandi:true},mime_turu:{dogrulandi:true},checksum:{dogrulandi:true,edge_makbuzu_dogrulandi:true},tamamlanma_tarihi:new Date().toISOString()},kapak_iptal_edildi:true,transkript:{durum:"yok"}};
  const arac=(await c.query(`INSERT INTO public.ogrenme_araclari(talep_id,iu_id,arac_turu,kaynak,dosya_yolu,mime_type,dosya_boyutu,checksum_sha256,metadata,metadata_dogrulandi) VALUES($1,NULL,$2,'hazir',$3,$4,1024,$5,$6::jsonb,$7) RETURNING arac_id`,[talep.talep_id,tur,`test/${talep.talep_id}/${tur}`,mime,"b".repeat(64),JSON.stringify(meta),tur==="podcast"])).rows[0];
  await c.query("INSERT INTO public.ogrenme_araci_durumu(arac_id,durum,degistiren_id) VALUES($1,'dogrulama_bekliyor',$2)",[arac.arac_id,t.uretici_id]);const key=randomUUID();
  if(tur==="gorsel")await c.query("SELECT public.uretim_gorsel_dogrula($1,$2,NULL,1200,1600,$3)",[arac.arac_id,t.uretici_id,key]);else if(tur==="flip_pdf")await c.query("SELECT public.uretim_flip_pdf_dogrula($1,$2,NULL,4,'Test','tam',$3)",[arac.arac_id,t.uretici_id,key]);else await c.query("SELECT public.uretim_podcast_dogrula($1,$2,NULL,60,$3)",[arac.arac_id,t.uretici_id,key]);
  if(!hazirSoru){const g=(await c.query("SELECT * FROM public.uretim_gorevleri WHERE talep_id=$1 AND asama='soru_seti'",[talep.talep_id])).rows[0];assert.ok(g?.atanan_iu_id);if(g.durum==="atama_bekliyor")await c.query("UPDATE public.uretim_gorevleri SET durum='hazirlaniyor' WHERE gorev_id=$1",[g.gorev_id]);await c.query("SELECT public.uretim_soru_seti_teslim_et($1,$2,$3::jsonb,$4)",[g.gorev_id,g.atanan_iu_id,JSON.stringify(sorular),randomUUID()]);const gi=(await c.query("SELECT surum FROM public.uretim_gorevleri WHERE gorev_id=$1",[g.gorev_id])).rows[0];await c.query("SELECT public.uretim_uretici_karar_ver($1,$2,'onaylandi',NULL,$3,$4)",[g.gorev_id,t.uretici_id,randomUUID(),gi.surum]);}
  const ok=(await c.query(`SELECT EXISTS(SELECT 1 FROM public.ogrenme_araci_durumu WHERE arac_id=$1 AND durum='onaylandi') arac,EXISTS(SELECT 1 FROM public.soru_setleri s JOIN public.soru_seti_durumu d USING(soru_seti_id) WHERE s.talep_id=$2 AND d.durum='onaylandi') soru`,[arac.arac_id,talep.talep_id])).rows[0];assert.deepEqual(ok,{arac:true,soru:true});sonuc.push({tur,varyant,tamamlandi:true});console.log(JSON.stringify(sonuc.at(-1)));await c.query("ROLLBACK TO SAVEPOINT v");await c.query("RELEASE SAVEPOINT v");}
 console.log(JSON.stringify({sonuc,rollback:true}));}finally{await c.query("ROLLBACK").catch(()=>{});await c.end();}}
main().catch(e=>{console.error(e.message);process.exitCode=1});
